# .gitlab-ci.yml
# File ID: 310b1b8c-8e3d-11ef-bead-83850402c3ce

image: gcc

variables:
  LC_ALL: "C.UTF-8"

geocalc:linux:
  stage: build
  before_script:
  script:
    - script -e -q -c "make testall clean tlokall DEVEL=1"
