.\" geocalc.1.man
.\" File ID: f97aa59c-92bb-11ef-95a5-83850402c3ce
.TH GEOCALC 1 "RPL_DATE" "geocalc\-RPL_VERSION"
.SH NAME
geocalc \- Calculate various geographic data
.SH SYNOPSIS
.B geocalc
[\fIOPTIONS\fP] <\fICOMMAND\fP> [\fIARGS\fP]
.SH DESCRIPTION
geocalc is a program that calculates various geographic data. It receives 
parameters and values via the command line, and prints strict, stripped-down 
values to standard output. This makes it suitable for use in scripts and quick 
manual calculations.
.SS Features
.IP \[bu] 2
Distance calculations between coordinates
.IP \[bu] 2
Bearing calculations
.IP \[bu] 2
Plot shortest route between points
.IP \[bu] 2
Minimal dependencies, no extra C libraries needed
.IP \[bu] 2
Platform independent
.IP \[bu] 2
Built-in test suite for all functionality
.SH OPTIONS
.TP
\fB\-h\fP, \fB\-\-help\fP
Show a help summary.
.TP
\fB\-\-km\fP
Use kilometers instead of meters in the input and output.
.TP
\fB\-\-license\fP
Print the software license.
.TP
\fB\-q\fP, \fB\-\-quiet\fP
Be more quiet. Can be repeated to increase silence.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Increase level of verbosity. Can be repeated.
.TP
\fB\-\-selftest\fP
Run the built-in test suite.
.TP
\fB\-\-valgrind\fP
Run the built-in test suite and use additional Valgrind checking.
.TP
\fB\-\-version\fP
Print version information.
.SH COMMANDS
All coordinates must be entered as decimal degrees, using the format 
\fB[\-]xxx.yyyyy\fP. Only metric units are supported; distances are printed in 
meters or kilometers, and distance inputs are also expected to be in meters or 
kilometers.
.PP
Some arguments are specified as a coordinate. One format is allowed: 
\fBlat,lon\fP where \fIlat\fP and \fIlon\fP is a number in the range \-90..90 
and \-180..180, separated by a comma. The decimal comma must be a period, '.'.
.TP
\fBbear\fP <\fIcoor1\fP> <\fIcoor2\fP>
Prints initial compass bearing (0\-360) between two points.
.TP
\fBbpos\fP <\fIcoor\fP> <\fIbearing\fP> <\fIdistance\fP>
Calculates the new geographic position after moving \fIdistance\fP meters from 
the position \fIcoor\fP in direction \fIbearing\fP. Negative values for 
\fIdistance\fP are allowed, to make it possible to calculate positions in the 
opposite direction of \fIbearing\fP.
.TP
\fBcourse\fP <\fIcoor1\fP> <\fIcoor2\fP> <\fInum\fP>
Generates a list of \fInum\fP intermediate points on a direct line between two 
locations. If a value of 0 is specified, only the begin and end positions are 
printed.
.TP
\fBdist\fP <\fIcoor1\fP> <\fIcoor2\fP>
Calculates the distance between two geographic points, using the Haversine 
formula. The result (in meters or kilometers) is printed to standard output.
.TP
\fBlpos\fP <\fIcoor1\fP> <\fIcoor2\fP> <\fIfracdist\fP>
Prints the position of a point on a straight line between the locations, where 
\fIfracdist\fP is a fraction that specifies how far along the line the point 
is. 0 = start position, 1 = end position. \fIfracdist\fP can also take values 
below 0 or above 1 to calculate positions beyond \fIcoor2\fP or in the opposite 
direction from \fIcoor1\fP.
.SH EXIT STATUS
.TP
0
No error.
.TP
1
Some error occurred, for example invalid coordinates or numbers were provided.
.SH EXAMPLES
.TP
\fCgeocalc bear 60.393,5.324 51.53217,\-0.17786\fP
Find the bearing towards Abbey Road Studios when standing in the middle of 
Bergen, Norway.
.TP
\fCgeocalc bpos 40.80542,\-73.96546 188.7 4817.84\fP
Determine the new position when traveling 4817.84 meters from the "Seinfeld 
Café" along a bearing of 188.7 degrees, heading slightly southwest.
.TP
\fCgeocalc course 52.3731,4.891 35.681,139.767 1000\fP
Create 1000 intermediate points on a straight line from Amsterdam to Tokyo.
.TP
\fCgeocalc \-\-km dist 90,0 \-90,0\fP
Calculate the distance from the North Pole to the South Pole and use kilometers 
in the result.
.TP
\fCgeocalc lpos \-11.952039,49.245985 \-25.606629,45.167246 0.5\fP
Find center point on Madagascar, measured from the points furthest north and 
south.
.SH AUTHOR
Written by \[/O]yvind A.\& Holm <sunny@sunbase.org>
.SH COPYRIGHT
(C)opyleft 2024\- \[/O]yvind A.\& Holm <sunny@sunbase.org>
.PP
This program is free software; you can redistribute it and/or modify it under 
the terms of the GNU General Public License as published by the Free Software 
Foundation; either version 2 of the License, or (at your option) any later 
version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE.
.PP
See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with 
this program. If not, see <http://www.gnu.org/licenses/>.
