.\" geocalc.1.man
.\" File ID: f97aa59c-92bb-11ef-95a5-83850402c3ce
.TH geocalc 1 "RPL_DATE" "geocalc\-RPL_VERSION"
.SH NAME
geocalc \- Calculate various geographic data
.SH SYNOPSIS
.B geocalc
[\fIOPTIONS\fP] <\fICOMMAND\fP> [\fIARGS\fP]
.SH DESCRIPTION
Calculates various geographic data. Input values are provided through command 
line arguments, and the result is printed to standard output.
.TP
\fB\-h\fP, \fB\-\-help\fP
Show a help summary.
.TP
\fB\-\-license\fP
Print the software license.
.TP
\fB\-q\fP, \fB\-\-quiet\fP
Be more quiet. Can be repeated to increase silence.
.TP
\fB\-v\fP, \fB\-\-verbose\fP
Increase level of verbosity. Can be repeated.
.TP
\fB\-\-selftest\fP
Run the built\-in test suite.
.TP
\fB\-\-version\fP
Print version information.
.SH COMMANDS
All coordinates must be entered as decimal degrees, using the format 
\fB[-]xxx.yyyyy\fP. Only metric units are supported; distances are printed in 
meters, and distance inputs are also expected to be in meters.
.TP
\fBbear\fP <\fIlat1\fP> <\fIlon1\fP> <\fIlat2\fP> <\fIlon2\fP>
Print initial compass bearing (0-360) between two points.
.TP
\fBbpos\fP <\fIlat\fP> <\fIlon\fP> <\fIbearing\fP> <\fIdistance\fP>
Calculates the new geographic position after moving \fIdistance\fP meters from 
the position \fIlat\fP,\fIlon\fP in direction \fIbearing\fP. Negative values 
for \fIdistance\fP are allowed, to make it possible to calculate positions in 
the opposite direction of \fIbearing\fP.
.TP
\fBdist\fP <\fIlat1\fP> <\fIlon1\fP> <\fIlat2\fP> <\fIlon2\fP>
Calculate the distance between two geographic points, using the Haversine 
formula. The result (in meters) is printed to standard output.
.SS Exit status:
.TP
0
No error.
.TP
1
Some error occurred, for example invalid coordinates or numbers were provided.
.SH EXAMPLES
.TP
geocalc bear 60.393 5.324 51.53217 \-0.17786
Find the bearing towards Abbey Road Studios when standing in the middle of 
Bergen, Norway.
.TP
geocalc bpos 40.80542 \-73.96546 188.7 4817.84
Determine the new position when traveling 4817.84 meters from the "Seinfeld 
Café" along a bearing of 188.7 degrees, heading slightly southwest.
.TP
geocalc dist 90 0 \-90 0
Calculate the distance from the North Pole to the South Pole.
.SH AUTHOR
Written by \[/O]yvind A. Holm <sunny@sunbase.org>
.SH COPYRIGHT
(C)opyleft 2024\- \[/O]yvind A. Holm <sunny@sunbase.org>
.PP
This program is free software; you can redistribute it and/or modify it under 
the terms of the GNU General Public License as published by the Free Software 
Foundation; either version 2 of the License, or (at your option) any later 
version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE.
.PP
See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with 
this program. If not, see <http://www.gnu.org/licenses/>.
