/*
 * strings.c
 * File ID: f7f16c5c-96b1-11ef-bd3d-83850402c3ce
 *
 * (C)opyleft 2024- Øyvind A. Holm <sunny@sunbase.org>
 *
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free 
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "geocalc.h"

/*
 * mymalloc() - Wrapper around malloc(), display error message if the 
 * allocation fails. Returns the value from malloc().
 */

void *mymalloc(const size_t size)
{
	void *v = malloc(size);

	if (!v) {
		myerror("%s(): Memory allocation error" /* gncov */
		        " (%zu bytes)", __func__, size);
	}

	return v;
}

/*
 * string_to_double() - Converts a number from `char *` to `double` and checks 
 * for errors. If any error occurs, it sets `errno` and returns 1, otherwise it 
 * returns 0.
 */

int string_to_double(const char *s, double *dest)
{
	char *endptr;
	errno = 0;

	*dest = strtod(s, &endptr);

	if (errno == ERANGE) {
		/* Number is too large or small */
		return 1;
	}

	if (endptr == s) {
		/* No valid conversion possible */
		errno = EINVAL;
		return 1;
	}

	/*
	 * Check for extra characters after the number, whitespace and `,` are 
	 * allowed for the time being in case it's copy+paste.
	 */
	while (*endptr != '\0') {
		if (*endptr != ',' && !isspace((unsigned char)*endptr)) {
			errno = EINVAL;
			return 1;
		}
		endptr++;
	}

	if (isnan(*dest)) {
		errno = EINVAL;
		return 1;
	}

	if (isinf(*dest)) {
		errno = ERANGE;
		return 1;
	}

	return 0;
}

/*
 * mystrdup() - Custom implementation of `strdup()`, which isn't available in 
 * C99. Returns a pointer to an allocated duplicate of `s`. If `malloc()` fails 
 * or `s` is NULL, it returns NULL.
 */

char *mystrdup(const char *s)
{
	size_t size;
	char *p;

	if (!s)
		return NULL;
	size = strlen(s);
	p = malloc(size + 1);
	if (!p) {
		myerror("%s(): Could not allocate %zu bytes", /* gncov */
		        __func__, size);
		return NULL; /* gncov */
	}
	memcpy(p, s, size);
	p[size] = '\0';

	return p;
}

/*
 * allocstr() - Return pointer to allocated string generated by providing 
 * printf()-like arguments. Returns NULL on error.
 */

char *allocstr(const char *format, ...)
{
	va_list ap;
	char *p;
	size_t size = BUFSIZ;

	assert(format);

	p = malloc(size);
	if (!p) {
		myerror("%s(): Cannot allocate %u bytes", /* gncov */
		        __func__, size);
		return NULL; /* gncov */
	}

	while (1) {
		int i;
		char *p2;

		va_start(ap, format);
		i = vsnprintf(p, size, format, ap);
		va_end(ap);

		if (i < 0) {
			myerror("%s(): Cannot write %s bytes" /* gncov */
			        " to memory buffer", __func__, size);
			return NULL; /* gncov */
		}

		if ((size_t)i < size)
			return p;

		size += BUFSIZ;

		p2 = realloc(p, size);
		if (!p2) {
			myerror("%s(): Cannot reallocate %u bytes", /* gncov */
			        __func__, size);
			free(p); /* gncov */
			return NULL; /* gncov */
		}
		p = p2;
	}
}

/*
 * parse_coordinate() - Parse the geographic coordinate in `s` and store 
 * latitude and longitude in `dest_lat` and `dest_lon`. The coordinate must be 
 * in the format `[-]dd.dddddd,[-]ddd.dddddd` (lat,lon) where the numbers are 
 * in the range -90..90 and -180..180. If it's not a valid coordinate or if 
 * anything fails, the function returns 1. If successful, it returns 0.
 *
 * There is intentionally no range check in this function, to make it more 
 * universal. Functions that use this function must validate the values 
 * themselves.
 */

int parse_coordinate(const char *s, double *dest_lat, double *dest_lon)
{
	char *comma, *sd;
	double lat, lon;
	int retval = 0;

	assert(dest_lat);
	assert(dest_lon);

	if (!s || !dest_lat || !dest_lon)
		return 1;
	if (!strchr(s, ','))
		return 1;
	sd = mystrdup(s);
	if (!sd) {
		myerror("%s(): mystrdup() failed", __func__); /* gncov */
		return 1; /* gncov */
	}
	comma = strchr(sd, ',');
	if (string_to_double(comma + 1, &lon)) {
		retval = 1;
		goto cleanup;
	}
	*comma = '\0';
	if (string_to_double(sd, &lat)) {
		retval = 1;
		goto cleanup;
	}
	*dest_lat = lat;
	*dest_lon = lon;

cleanup:
	free(sd);
	return retval;
}

/* vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 : */
