/*
 * strings.c
 * File ID: f7f16c5c-96b1-11ef-bd3d-83850402c3ce
 *
 * (C)opyleft 2024- Øyvind A. Holm <sunny@sunbase.org>
 *
 * This program is free software; you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free 
 * Software Foundation; either version 2 of the License, or (at your option) 
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for 
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with 
 * this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "geocalc.h"

/*
 * string_to_double() - Converts a number from `char *` to `double` and checks 
 * for errors. If any error occurs, it sets `errno` and returns 1, otherwise it 
 * returns 0.
 */

int string_to_double(const char *s, double *dest)
{
	char *endptr;

	assert(s);
	assert(dest);

	*dest = strtod(s, &endptr);

	if (errno == ERANGE) {
		/* Number is too large or small */
		return 1;
	}

	if (endptr == s) {
		/* No valid conversion possible */
		errno = EINVAL;
		return 1;
	}

	/*
	 * Check for extra characters after the number, whitespace and `,` are 
	 * allowed for the time being in case it's copy+paste.
	 */
	while (*endptr != '\0') {
		if (*endptr != ',' && !isspace((unsigned char)*endptr)) {
			errno = EINVAL;
			return 1;
		}
		endptr++;
	}

	if (isnan(*dest)) {
		errno = EINVAL;
		return 1;
	}

	if (isinf(*dest)) {
		errno = ERANGE;
		return 1;
	}

	return 0;
}

/*
 * trim_zeros() - Trims trailing zeros from the decimal number in `s`, keeping 
 * the decimal point with one zero if present. Returns `s` immediately if:
 *
 * - `s` is NULL or empty
 * - there is no period ('.') in the string
 * - string_to_double() fails to parse the number
 * - there are any characters other than [0-9], '+', '-', or '.' in the string
 *
 * Trailing zeros after the decimal point are removed, but the decimal point 
 * and one zero are kept (e.g., "5.00000" becomes "5.0"). Zeros at the start or 
 * before the decimal point are preserved. The function modifies `s` directly, 
 * so pass a copy if the original string must be kept. Returns `s`.
 */

char *trim_zeros(char *s)
{
	char *p;
	double d;

	assert(s);

	if (!s || !*s)
		return s;
	if (!strchr(s, '.'))
		return s;
	if (string_to_double(s, &d))
		return s;
	for (p = s; *p; p++) {
		if (!strchr("0123456789+-.", *p))
			return s; /* gncov */
	}

	p--;
	while (p > s + 1 && *p == '0' && *(p - 1) != '.')
		*p-- = '\0';

	return s;
}

/*
 * mystrdup() - Custom implementation of `strdup()`, which isn't available in 
 * C99. Returns a pointer to an allocated duplicate of `s`. If `malloc()` fails 
 * or `s` is NULL, it returns NULL.
 */

char *mystrdup(const char *s)
{
	size_t size;
	char *p;

	if (!s)
		return NULL;
	size = strlen(s);
	p = malloc(size + 1);
	if (!p)
		return NULL; /* gncov */
	memcpy(p, s, size);
	p[size] = '\0';

	return p;
}

/*
 * allocstr_va() - Returns pointer to allocated string generated by providing 
 * printf()-like format and va_list. Returns NULL on error.
 */

char *allocstr_va(const char *format, va_list ap)
{
	char *p;
	int needed;
	va_list ap_copy;
	size_t size;

	assert(format);
	if (!format)
		return NULL; /* gncov */

	va_copy(ap_copy, ap);
	needed = vsnprintf(NULL, 0, format, ap_copy);
	va_end(ap_copy);

	if (needed < 0)
		return NULL; /* gncov */

	size = (size_t)needed + 1;
	p = malloc(size);
	if (!p)
		return NULL; /* gncov */

	needed = vsnprintf(p, size, format, ap);
	if (needed < 0) {
		free(p); /* gncov */
		return NULL; /* gncov */
	}

	return p;
}

/*
 * allocstr() - Returns pointer to an allocated string generated by providing 
 * printf()-like arguments. Returns NULL on error.
 */

char *allocstr(const char *format, ...)
{
	va_list ap;
	char *retval;

	assert(format);
	if (!format)
		return NULL; /* gncov */

	va_start(ap, format);
	retval = allocstr_va(format, ap);
	va_end(ap);

	return retval;
}

/*
 * count_substr() - Returns the number of non-overlapping occurrences of 
 * substring `substr` in string `s`.
 */

size_t count_substr(const char *s, const char *substr)
{
	size_t count = 0, len_ss;
	const char *p = s;

	if (!s || !substr || !*s || !*substr)
		return 0;

	len_ss = strlen(substr);
	while ((p = strstr(p, substr)) != NULL) {
		count++;
		p += len_ss;
	}

	return count;
}

/*
 * str_replace() - Returns an allocated string where all substrings `s1` are 
 * replaced with the string `s2` in the string `s`.
 *
 * Returns NULL if any errors occur or if `s`, `s1` or `s2` are NULL.
 *
 * If `s1` is empty, an allocated copy of `s` is returned.
 */

char *str_replace(const char *s, const char *s1, const char *s2)
{
	size_t len_s1, len_s2, count, new_len;
	const char *tmp, *src;
	char *buf, *dest;

	if (!s || !s1 || !s2)
		return NULL;

	len_s1 = strlen(s1);
	len_s2 = strlen(s2);
	count = count_substr(s, s1);

	if (!*s || !*s1 || !count)
		return allocstr("%s", s);

	new_len = strlen(s) + count * (len_s2 - len_s1);
	buf = malloc(new_len + 1);
	if (!buf)
		return NULL; /* gncov */

	dest = buf;
	src = s;
	while ((tmp = strstr(src, s1)) != NULL) {
		size_t len_before = (size_t)(tmp - src);

		memcpy(dest, src, len_before);
		dest += len_before;

		memcpy(dest, s2, len_s2);
		dest += len_s2;

		src = tmp + len_s1;
	}
	strcpy(dest, src);

	return buf;
}

/*
 * parse_coordinate() - Parses the geographic coordinate in `s` and stores 
 * latitude and longitude in `dest_lat` and `dest_lon`. The coordinate must be 
 * in the format `[-]dd.dddddd,[-]ddd.dddddd` (lat,lon) where the numbers are 
 * in the range -90..90 and -180..180.
 *
 * If `validate` is `true`, it validates the coordinate range and returns 1 if 
 * the values are outside the valid range.
 *
 * If it's not a valid coordinate or if anything fails, the function returns 1. 
 * If successful, it returns 0.
 */

int parse_coordinate(const char *s, bool validate,
                     double *dest_lat, double *dest_lon)
{
	char *comma, *sd;
	double lat, lon;
	int retval = 0;

	assert(dest_lat);
	assert(dest_lon);

	if (!s || !dest_lat || !dest_lon)
		return 1;
	if (!strchr(s, ','))
		return 1;
	sd = mystrdup(s);
	if (!sd) {
		failed("mystrdup()"); /* gncov */
		return 1; /* gncov */
	}
	comma = strchr(sd, ',');
	if (string_to_double(comma + 1, &lon)) {
		retval = 1;
		goto cleanup;
	}
	*comma = '\0';
	if (string_to_double(sd, &lat)) {
		retval = 1;
		goto cleanup;
	}
	*dest_lat = lat;
	*dest_lon = lon;

	if (validate && (fabs(lat) > 90.0 || fabs(lon) > 180.0))
		retval = 1;

cleanup:
	free(sd);

	return retval;
}

/* vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 : */
